name: publish npm package and update version
on: 
  push:
    branches:
      - master
jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: build-storybook
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: build book
      run: |
        npm install
        echo "aaa        akjndejkwdnwjkendwwedwkjd-------------------------------------------------------"
        echo "${{ secrets.NODE_AUTH_TOKEN }}"
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        CI: false